### ISSUE TITLE
P2: Make Airbnb iCal sync durable before checkout availability proceeds

### ISSUE THREAD

**Issue by SebCorner08** [SebCorner08/apartment-booking-app#66]
## Problem

Current `main@d3f9169deab84f9bd133576dddd593f8e7ef3232` treats Airbnb calendar fetch completion as if database synchronization were complete, but `server/services/calendar-service.js::syncAirbnbCalendar()` queues the `external_blocks` upserts/deletes with callback-style `db.run()` calls and does not await their completion.

Consequences:
- `syncAirbnbCalendar()` can log success and call `broadcastAdminUpdate()` before the SQLite writes have completed;
- individual SQLite write failures are only logged and are not propagated to the caller;
- the empty-feed delete path does not attach an error callback;
- `server/routes/payment-routes.js` does `if (airbnbIcalUrl) await syncAirbnbCalendar();` immediately before `bookingService.createHold(...)`, but the awaited promise currently resolves without proving that the external-block writes succeeded.

The exact-head Data review on recovery PR #58 independently identified this as a pre-existing persistence risk: FIFO ordering on the single SQLite connection helps normal ordering, but write failures are not propagated and broadcast can happen before callbacks finish. This was not introduced by #58.

Production currently reports `AIRBNB_ICAL_URL` unset, so Airbnb synchronization is disabled. This makes the defect dormant today, but it should be resolved before enabling Airbnb sync as a production availability source.

## Ownership

- Implementation owner: `AGT-DATA-001` — Database & Payments.
- Principal / `AGT-LEAD-001` coordinates sequencing/integration only and does not implement Data-owned persistence changes.
- `AGT-QA-001` provides independent QA.
- Copilot is reviewer-only after the mandatory exact-head QA gate and must never implement fixes.

## Scope

- Make one Airbnb sync operation complete only after all required `external_blocks` persistence work is durably complete.
- Propagate a persistence failure to the checkout caller instead of allowing availability/hold creation to proceed as if the sync succeeded.
- Broadcast an admin update only after the synchronization persistence has completed successfully.
- Prefer one coherent transactional apply of feed upserts plus stale-UID deletion so a partially applied feed cannot silently become the accepted availability state.
- Cover the empty-feed deletion path with the same durable/error semantics.
- Preserve existing schema, source/UID uniqueness, booking/pricing/payment semantics and server-authoritative availability rules.
- Do not enable or change `AIRBNB_ICAL_URL` as part of this issue; production configuration remains a separate Repository Owner decision under #14.

## Acceptance criteria

- `await syncAirbnbCalendar()` resolves only after every required SQLite write for that feed has succeeded.
- Any required database write failure causes the sync to fail observably and prevents `/api/create-checkout-session` from proceeding to hold/session creation on a falsely synchronized availability state.
- No success log/admin broadcast occurs before durable completion and no success broadcast occurs on failed/rolled-back sync.
- Feed upserts and stale-block deletion have explicit atomicity/rollback semantics.
- Empty-feed cleanup is awaited and failure-aware.
- Isolated regression tests cover delayed writes, injected upsert failure, injected stale-delete failure, empty-feed cleanup, rollback/partial-write prevention and checkout fail-closed behavior. Tests must not use production data or live Stripe/Airbnb calls.
- `AGT-DATA-001` posts `RESULT_SUBMITTED` for the exact final candidate with before/after data flow, tests and rollback/compatibility notes.
- Independent same-SHA `AGT-QA-001 QA_CONFORM` is required before any Copilot reviewer request.
- Only after QA may Copilot be explicitly requested reviewer-only. Findings return to `AGT-DATA-001`; Copilot must not implement fixes.
- Any material change requires renewed affected QA and a fresh Copilot review.
- Raelvi performs final technical review on the exact unchanged cleared head.
- Merge, deployment, production configuration and destructive data operations require separate explicit Repository Owner authorization.

## Sequencing

This is a follow-up persistence issue discovered during #8 recovery review. Do not start it ahead of the current P1 #62 ownership/release blocker. If the Repository Owner chooses to enable `AIRBNB_ICAL_URL` under #14 before this issue is cleared, explicitly record acceptance of this known availability-integrity risk rather than treating the sync path as fully verified.

No implementation code, branch, PR, Copilot request, production configuration, deploy or production-data operation is authorized by creating this issue.
